<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN617480" failures="30" tests="260" name="com.vitalGuard.tests.TestRunner" time="142.350" errors="0" timestamp="2025-07-06T18:36:46 IST" skipped="0">
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.178"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.148"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.165"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.149"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.263"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.190"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.155"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.168"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.156"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="valNavbarlink" time="0.147"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.740"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.861"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.659"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.756"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.795"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.682"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.769"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.611"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.696"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.676"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.628"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.843"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.779"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.730"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.708"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.746"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.657"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.001"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.715"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.753"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.808"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.077"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.632"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.802"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.718"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.760"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.716"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.854"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.929"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.738"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.690"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.744"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.772"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.691"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.840"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.700"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.723"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.848"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.616"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.735"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.874"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.722"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.001"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="1.431"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.732"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuardCalculate" time="0.754"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.674"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.740"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.742"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.895"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.612"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.704"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.797"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.650"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.681"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.699"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.707"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.676"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.729"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.655"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.695"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.742"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.850"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.670"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.822"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.633"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.642"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.766"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.746"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.824"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.696"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.728"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.730"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.750"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.640"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.803"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.680"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.738"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.643"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.691"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.697"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.793"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.728"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.729"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.754"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.735"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.840"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.756"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.742"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.778"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.710"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard" time="0.733"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.145"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.139"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.183"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.161"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.136"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.179">
    <failure message="Error message mismatch for age input: 12.5 expected [Age must be an integer.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 12.5 expected [Age must be an integer.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidAgeInput(TestRunner.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidAgeInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.190"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.145"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.144"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeInput" time="0.140">
    <failure message="Error message mismatch for age input: 12.5 expected [Age must be an integer.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 12.5 expected [Age must be an integer.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidAgeInput(TestRunner.java:255)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidAgeInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.162"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.145"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.143"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.139">
    <failure message="Error message mismatch for pulse input: 100.5 expected [Pulse rate must be an integer.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for pulse input: 100.5 expected [Pulse rate must be an integer.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidPulseInput(TestRunner.java:264)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidPulseInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.136"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.149"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.153"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.152"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.163"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.147"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.193"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.149"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.149"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.125"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.185">
    <failure message="Error message mismatch for pulse input: 100.5 expected [Pulse rate must be an integer.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for pulse input: 100.5 expected [Pulse rate must be an integer.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidPulseInput(TestRunner.java:264)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidPulseInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseInput" time="0.122"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.127">
    <failure message="Error message mismatch for BP input:  expected [Use format: systolic/diastolic (e.g., 120/80)] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input:  expected [Use format: systolic/diastolic (e.g., 120/80)] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.159"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.200"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.198"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.118"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.140">
    <failure message="Error message mismatch for BP input:  expected [Use format: systolic/diastolic (e.g., 120/80)] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input:  expected [Use format: systolic/diastolic (e.g., 120/80)] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.136"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.219"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.122">
    <failure message="Error message mismatch for BP input: 150/80 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 150/80 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.138"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.185"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.116">
    <failure message="Error message mismatch for BP input: 150/80 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 150/80 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.160"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.138"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.156"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.190"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.116"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.153"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.166">
    <failure message="Error message mismatch for BP input: 999/999 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 999/999 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.165"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.166">
    <failure message="Error message mismatch for BP input: 999/999 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 999/999 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.164">
    <failure message="Error message mismatch for BP input: 120/95 expected [Diastolic must be between 60 and 90] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 120/95 expected [Diastolic must be between 60 and 90] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.146"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.183"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.167">
    <failure message="Error message mismatch for BP input: 85/80 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 85/80 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.152"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.145">
    <failure message="Error message mismatch for BP input: 85/80 expected [Systolic must be between 90 and 140] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 85/80 expected [Systolic must be between 90 and 140] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.174">
    <failure message="Error message mismatch for BP input: 120/55 expected [Diastolic must be between 60 and 90] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 120/55 expected [Diastolic must be between 60 and 90] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.131">
    <failure message="Error message mismatch for BP input: 120/95 expected [Diastolic must be between 60 and 90] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 120/95 expected [Diastolic must be between 60 and 90] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPInput" time="0.161">
    <failure message="Error message mismatch for BP input: 120/55 expected [Diastolic must be between 60 and 90] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for BP input: 120/55 expected [Diastolic must be between 60 and 90] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidBPInput(TestRunner.java:274)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPInput -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.645"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.788"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.627"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.616"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.644"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.743"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.698"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.615"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.589"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.756"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.717"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.617"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.622"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.810"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.784"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.683"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.595"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="1.022"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.697"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.642"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.609"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.762"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.645"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.771"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.516"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.782"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.811"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.627"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.711"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.811"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.624"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.750"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.784"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.649"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.709"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.732"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.795"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.679"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.763"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.787"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.778"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.606"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.798"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.745"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.583"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateVitalGuard2" time="0.568"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.215"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.388"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.264"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.268"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.303"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.266"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.342">
    <failure message="Error message mismatch for age input: 12.5 expected [Please enter a valid age between 1 and 120.] but found [Please enter a valid pulse rate between 40 and 180 bpm.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 12.5 expected [Please enter a valid age between 1 and 120.] but found [Please enter a valid pulse rate between 40 and 180 bpm.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidAgeAlert(TestRunner.java:355)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidAgeAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.272"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.306"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidAgeAlert" time="0.292">
    <failure message="Error message mismatch for age input: 12.5 expected [Please enter a valid age between 1 and 120.] but found [Please enter a valid pulse rate between 40 and 180 bpm.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 12.5 expected [Please enter a valid age between 1 and 120.] but found [Please enter a valid pulse rate between 40 and 180 bpm.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidAgeAlert(TestRunner.java:355)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidAgeAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.431"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.412">
    <failure message="Error message mismatch for age input: 100.5 expected [Please enter a valid pulse rate between 40 and 180 bpm.] but found [Please enter blood pressure in the format systolic/diastolic (e.g., 120/80).]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 100.5 expected [Please enter a valid pulse rate between 40 and 180 bpm.] but found [Please enter blood pressure in the format systolic/diastolic (e.g., 120/80).]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidPulseAlert(TestRunner.java:368)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidPulseAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.408"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.393"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.423"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.452"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.446"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.414">
    <failure message="Error message mismatch for age input: 100.5 expected [Please enter a valid pulse rate between 40 and 180 bpm.] but found [Please enter blood pressure in the format systolic/diastolic (e.g., 120/80).]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch for age input: 100.5 expected [Please enter a valid pulse rate between 40 and 180 bpm.] but found [Please enter blood pressure in the format systolic/diastolic (e.g., 120/80).]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.vitalGuard.tests.TestRunner.validateInvalidPulseAlert(TestRunner.java:368)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidPulseAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.399"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.415"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.422"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.478"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.436"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.384"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.472"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidPulseAlert" time="0.435"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.638"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.570"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.595"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.615"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.545"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.726"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.768">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.706">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.674"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.666"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.451"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.714">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.585">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.620"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.662"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.549">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.538"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.766"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.476"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.615"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.708"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.642"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.579">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.744">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.567"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.663">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.526">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.597"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.633"/>
  <testcase classname="com.vitalGuard.tests.TestRunner" name="validateInvalidBPAlert" time="0.630">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.vitalGuard.tests.TestRunner.validateInvalidBPAlert(TestRunner.java:387)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- validateInvalidBPAlert -->
</testsuite> <!-- com.vitalGuard.tests.TestRunner -->
